### ISSUE TITLE
Complete repo structure

### ISSUE THREAD

**Issue by riyaeliza123** [UBC-MDS/DSCI-532_2024_13_Juno#1]
- [x] README.md (the project title and a summary of its purpose in ~3-4 sentences)
- [x] LICENSE.md (include the license for both software and non-software content)
- [x] CODE_OF_CONDUCT.md (include a citation if you used a template from elsewhere)
- [x] CONTRIBUTING.md (include a citation if you used a template from elsewhere)
- [x] src/app.py or src/app.R (this file can be empty for now, but indicates which language you are planning to use)
- [x] data/raw/ (should inlucde your chosen raw data file(s); indicate in the proposal if you plan to load from an external source instead)
- [x] notebooks/ (optional: if you start doing EDA, include your notebooks in this folder)
- [x] environment.yml (can contain just the basics for now, e.g. the libraries for the dashboard, data wrangling, and vizualization; include version numbers)
- [x] reports/m1_proposal.md (see below)
- [x] img/sketch.png (see below)

**Comment by riyaeliza123** [comment]
Updates/comments:
1. sketch.png to be added, ticked ones are done, and templates have been added for readme and contributing
2. m1_proposal.md empty markdown added as placeholder

**Comment by riyaeliza123** [comment]
m1_proposal is complete now. PR has been made

**Comment by gtmx23** [comment]
I think this is done right? Can I move it to the completed column?

**Comment by riyaeliza123** [comment]
Yup!
