### ISSUE TITLE
Dataset suggestions

### ISSUE THREAD

**Issue by riyaeliza123** [UBC-MDS/DSCI-532_2024_13_Juno#10]
Project inspiration: https://five32-dashboard-showcase.onrender.com/

Add your suggestion/comments/votes here

**Comment by riyaeliza123** [comment]
A dataset concerning direct marketing campaigns conducted by a Portuguese banking institution. The dataset was sourced from UC Irvine's Machine Learning Repository and can be accessed via the following link: https://archive.ics.uci.edu/dataset/222/bank+marketing.

**Comment by riyaeliza123** [comment]
https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3310050101
"Representation of women and men on boards of directors and in officer positions, by firm attributes"

**Comment by gtmx23** [comment]
Thank you for the datasets Riya! Based on your suggestions and our in-class discussions, we decided to go with the statcan data set :)
