### ISSUE TITLE
Feedback from Nicole Bidwell

### ISSUE THREAD

**Issue by nicolebid** [UBC-MDS/DSCI-532_2024_13_Juno#106]
Hi!

I enjoyed exploring your app. I think your intended purpose of making this type of data easily interpretable was really well done. The choice of graphs, along with organized structure and visually appealing colors, added to this interpretability.  Here are some suggestions on things you could include/modify.

Major

- `Filter on Province` and `Filter on Year selections`: It took a moment to realize which filters were affecting what output (also due to the need to scroll). You could have the `Filter on Province` at the very top, since it affects the cards at the top too. Then make 2 new filters specifically for the bar charts and group them all together with a shaded background or border so it’s clear they are together. This way you wouldn’t have to scroll at all when filtering for the bar charts too.  

- The bar charts could be horizontal instead. This would help with reading the current x-axis values and the counts on each bar. 

Minor

- You may want to set default values for the filter selections, so nans and empty charts don't result from clicking the "x". 

-  On the map tooltip you could change `prop_women` to `proportion of women` and `name` to `location`,  for ease of reading.

- Formatting: The titles on the bar charts could be bolded to match the line graph format for consistency. The axis labels of the line graph were showing up a bit squished.  Increasing the font size could help.

- The line graph is really effective. It provides significant information in a simple and easily understood way. It would be interesting to have the option to compare two provinces/territories at once here, by allowing users to select another location to plot on. 

Overall, well done!

**Comment by nicolebid** [comment]
Oh I forgot to mention.. I like how you included the `What is Juno?` button on the dashboard--really interesting backstory.

**Comment by karan-khubdikar** [comment]
Thank you Nicole for the detailed feedback. Will try to incorporate the suggestions we can.

**Comment by riyaeliza123** [comment]
All feedback has been addressed in separate issues
