### ISSUE TITLE
Feedback from Arturo Rey

### ISSUE THREAD

**Issue by AReyH** [UBC-MDS/DSCI-532_2024_13_Juno#107]
Overall, I am loving the dashboard! It's very intuitive and informative. I especially love the dropdown information on what Juno is. The informations was clearly conveyed, and the topic was intriguing. I would love to see more from Juno.

I loved how reactive and interactive the dashboard is. 

Feedback (minor because the website is overall amazing):
* The dashboard seems to render bigger than intended, as you have to scroll a bit to the right in order to see the legend of the map plot.
* This is more of a suggestion; do not use white (#FFFFFF) as a background color. I would suggest using a more bone white, like #F2F2F2.
* When removing all the filters, the graphs in the bottom go blank. I would suggest adding a message telling the user to apply filters in order to look at the graphs.
* Some of the labels on the x-axis overlap with the x-axis label, when using specific filters, like when querying for "Management of companies and enterprises" in Newfoundland and Labrador on 2017.

**Comment by riyaeliza123** [comment]
All feedback has been addressed in separate issues
