### ISSUE TITLE
Week-1 20240326 Lab Time Notes 

### ISSUE THREAD

**Issue by gtmx23** [UBC-MDS/DSCI-532_2024_13_Juno#11]
# Notes from Joel's Introduction
## Introduction
- Make sure there is a scenario - problem to solve, audience to address: eg for a client/task
- Make sure license allows public use
- Not decided on how TAs will work with the groups yet - Joel will start a Slack question on this
## Submission instructions
- Create repository under UBC MDS public organisation **Note - we might have to change our appname when we decide on what we choose**
- Need release - 0.1.0 etc with release notes: tell Joel and TAs what has been done since 
  - Title of every PR essentially
  - Manual creation of release/manual tagging will do
- Also need link to release as ipynb - markdown cell with a link so TAs can click on it
- Teamwork contract: separate md file, **not** part of GH repo
- Follow 524 guidelines on how to work in a GH flow with other contributors
- Need to work on feature branches and not to main -> make commits often and small commits at a time
- Issues should be created
  - keywords: close #25 eg
  - Issues should all be closed with PRs
- All code added should come from PR, pushed from a branch - 1 fix/feature/closely connected set
  - 1 approving review before pushing, no self pushing
  - **Might have to set this as default if it is alr not a default**
- Use squash and merge
  - Nice bc not bringing all commits into main branch git history
  - Usually commit squashed into title of PR
  - **Might have to make this a default setting, follow milestone instructions**
 ## Proposal
- Main part of M1
- Think about purpose of dashboard and who we are designing for before coding
- Sketch - description of how app works
- Instructions in M1 are explicit - specific questions and write up on what it should look like
-  Don't spend too much time looking for data - not about finding optimum set
  - Ideally choose this week, can combine/split up data if you want
- Make sure data has open license
- Think about who is using your dashboard!
  - Persona: who is the user
  - Create a user story
- Sketch for app can be hand drawn/done on PowerPoint
- Optional to be at lab

# Team Work (further discussion in separate issue)
## Team Contract
Reference: https://docs.google.com/document/d/11jDEnCHJFVd2MzInQQ7yaM2nTVsV1uBa5HO6qpLc1hg/edit
Thanks @scout-mckee!
## Project board
Already exists, thanks @riyaeliza123!
## Discussion on work style 
- Scout will be away this weekend
- Riya will be working remotely for first 2 weeks

**Comment by karan-khubdikar** [comment]
Thanks, Gretel for such elaborate notes! And thanks Scout for drafting the contract.

**Comment by gtmx23** [comment]
# Discussion
## Team Work Contract
https://docs.google.com/document/d/1wqK5UmO6ox1IiF7sB7tAzKNCMkPuoYbLtr6mrOKAUTo/edit#heading=h.vmkslqnit46x
^ This is done, just need to make it into an MD style document

## Dataset
- Statcan one from Riya https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=3310050101
  - Scout thinks: Not a lot of percentages but a lot of filter options - might be interesting for visualisation
 - Karan is passionate about healthcare but there are limitations with that data because it is sensitive
 - Gretel likes women's issues!
- We have agreed to go with this data set, thanks everyone for the efficient discussion XD
### Target audience
- Researchers and **policymakers** esp in the field of sociology
  - Policy makers
  - People who are interested in equity
  - Sociology researchers who want general understanding of trends in gender and employment
## App name
- Girlboss(es)? Since our dataset is about women in directorial positions @scout-mckee thanks for the suggestions XD
- who's the boss?
- Let us think about this and confirm this tomorrow + change our repo name!
  - Feel free to continue sending names on Slack, @gtmx23 will do an anonymous poll for us to decide 



## Timeline
### Today
- Finalise teamwork contract and change it to md format
- Finalise dataset (DONE)
- Repo structure (DONE)

**Comment by gtmx23** [comment]
## Section 1: Motivation and Purpose
In a few sentences, provide motivation for

>  why you are creating a dashboard:
> 
> Who is your target audience, and what role are you embodying?
> 
> What is the problem the target audience is facing and why is it important to solve?
> 
> How can your dashboard assist in solving this problem for the intended target audience?

Target audience
- Researchers and **policymakers** esp in the field of sociology
- Policy makers
- People who are interested in equity
- Sociology researchers who want general understanding of trends in gender and employment

Our role
- Consultancy group - putting down the facts

Problem
- A lot of data, want to give them tools to pinpoint where gender biases might be 
- Help them to focus on specific areas, help them to make efficient use of resources 
- Too much data!

Dashboard help
- Puts info in one place - easy to understand, interactive so you can change different filters
- If you see anomalies, can deep dive into it -> explore data in a way that is easy to understand and take in
- Don't have to do groundwork to get data and clean it etc since policymakers don't have the time to do it themselve
- Summarise important information - policymakers can easily explore both general and specific trends in gendered employment in an interactive way that best suits their policy needs

## Section 2: Description of data
Nothing much to discuss
- Download whole dataset without filters

## Section 3: Research questions and usage scenarios


> The purpose of this section is to get you to think in more detail about how your target audience will use the app you're designing and to account for these detailed needs in the proposal.

For this it can be helpful to create a [brief persona description](https://engineering-shiny.org/dont-rush-into-coding.html#building-personas) of a member in your intended target audience

Then, think about what they might want to do with your app and write small user story. User stories are typically written in a narrative style and include:

The specific context/background of the user

The overall goal of the user

Tasks needed to reach that goal

A hypothetical walkthrough of how the user would accomplish those tasks with your app

The outcome/action that the user would take based on the information they find in the app

- Policymaker - investigating gender bias and how it changes for diff sectors, provinces, over 4 year span
- Beginning stages of policymaking - what subsets might be most problematic, how trend is evolving across time in that province/sector, what interventions might they want to consider/stakeholders to consult
- Keep ideas flowing on Slack!

## Section 4
Section 4: App sketch & brief description

> Create a sketch of what you envision your app to look like. Your sketch can be hand-drawn or put together using a graphics editor or slide show software. The sketch should be saved as img/sketch.png and linked in this section of the proposal so that the image shows up when reading the proposal on GitHub.

- Map of Canada -> province stats
- Home page all of Canada, click to select which province you are interested in
Brainstorm! Pics on Slack
- Only looking at different ways to subset data, main info is on percentrage/number of females and males in directorial positions
- 3 different interactions - province, industry, time
- Fix industry trends as something to view overall
### Features to include
- Map of Canada as a filtering and visualisation tool
- Ability to see industries
  - All at once
  - Individual trends over time 
  - Fixed overall view based on industry because some industries are historically male/female dominated, so it is useful to have that as the overall context
- Filter by province, industry and time
- National average for comparison
- Homepage - national average, then we interact with it to 
- Notes from Joel - can look at group 22 from last year to see how they executed the map
  - If we don't get the interactive map working we can have a tab/dropdown for each province

**Comment by gtmx23** [comment]
## Work distribution
- [x] Repo set up: @riyaeliza123 (thanks for the initiative!)
- [x] Section 1: @scout-mckee 
- [x] Section 2: @riyaeliza123 
- [x] Section 3: @gtmx23 
- [x] Section 4: @karan-khubdikar 
- [x] Edit README: Whoever is done with their section first
- [x] Check on default settings + create issues for each section: @gtmx23 
- [x] Download team work contract: @scout-mckee 
- [x] Submission - Gradescope and GH release: @karan-khubdikar 
- [x] Review: Section 1 person will review for section 2 etc + whoever is approving the merge request will review more finely (so everyone)
- [x] Decide on name (everyone)
  - Suggestions open until tomorrow morning ~9am - @gtmx23 will create an anonymous poll for us to vote on the name! Then we can change this repo name :)

**Comment by karan-khubdikar** [comment]
Closing the issue as we are done with Milestone I
