### ISSUE TITLE
add numbers and labels to line chart

### ISSUE THREAD

**Issue by scout-mckee** [UBC-MDS/DSCI-532_2024_13_Juno#118]

**Comment by scout-mckee** [comment]
From Jerry: "Indicate numbers on line chart: because the ratios are quite similar, it is hard to tell the yearly changes. Labeling the ratio for each year on the chart would be a good idea to make it easier to read.

**Comment by riyaeliza123** [comment]
Tooltip has the numbers. Since the goal is to understand trends, we keep the numbers on tooltip (so that the user can view them if they wish). This way we don't overcrowd the chart.
