### ISSUE TITLE
MAIN TASK: Performance improvements

### ISSUE THREAD

**Issue by scout-mckee** [UBC-MDS/DSCI-532_2024_13_Juno#130]
- **Use a binary format for loading data faster**
- Have no redundant filtering/mutating of the data in the app
- Create a processed data file that is loaded in the app instead (stored in data/processed).
- Have no excessively slow computation that could be easily sped up, e.g. no row-wise use of apply unless well justified and optimized.
- Use caching for at least one function

**Comment by riyaeliza123** [comment]
Binary format done #138

**Comment by riyaeliza123** [comment]
caching done #167
