### ISSUE TITLE
Feedback from Joel M4

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_13_Juno#139]
Implement two major and three minor

Major:

- [x] #140
- [x] #141
- [x] #142

Minor:

- [x] #146
    - [x] Update natural average 
- [x] Use great for missing data in chart
- [ ] Think about collapse button, maybe to the side and expand the lavandar color?
- [x] #143
- [x] #145
- [x] #144

**Comment by karan-khubdikar** [comment]
Closing as most of the recommended changes have been implemented.
