### ISSUE TITLE
Section 4 Write Up

### ISSUE THREAD

**Issue by gtmx23** [UBC-MDS/DSCI-532_2024_13_Juno#16]
From main GH Issue https://github.com/UBC-MDS/DSCI-532_2024_13_appname/issues/11

> 
> Section 4: App sketch & brief description
> 
> Create a sketch of what you envision your app to look like. Your sketch can be hand-drawn or put together using a graphics editor or slide show software. The sketch should be saved as img/sketch.png and linked in this section of the proposal so that the image shows up when reading the proposal on GitHub.
> 
> Map of Canada -> province stats
> Home page all of Canada, click to select which province you are interested in
> Brainstorm! Pics on Slack
> Only looking at different ways to subset data, main info is on percentrage/number of females and males in directorial positions
> 3 different interactions - province, industry, time
> Fix industry trends as something to view overall
> Features to include
> Map of Canada as a filtering and visualisation tool
> Ability to see industries
> All at once
> Individual trends over time
> Fixed overall view based on industry because some industries are historically male/female dominated, so it is useful to have that as the overall context
> Filter by province, industry and time
> National average for comparison
> Homepage - national average, then we interact with it to
> Notes from Joel - can look at group 22 from last year to see how they executed the map
> If we don't get the interactive map working we can have a tab/dropdown for each province

**Comment by riyaeliza123** [comment]
This is complete
