### ISSUE TITLE
Week-2 20240402 Lab Time Notes

### ISSUE THREAD

**Issue by karan-khubdikar** [UBC-MDS/DSCI-532_2024_13_Juno#32]
# Week 2 Lab Notes: 
Hey team, just putting down some notes from the instructions given by Joel during the lab. We can make the necessary changes once we have the team meeting. 

**Checklist for the submission:**
- [x] Update the About section(link, description, topics)
- [x] Deploy the app on render website
- [x] Show at least 6 components (4 charts +2 widgets or similar combo)
- [x] Show in grid format (to be discussed in the lecture on Friday)
- [x] In the bottom, add the details about who made the dashboard, link to the repo, last update date, etc.
- [x] Reflection Section
- [x] Update Readme

### Reflection Section:
- What is implemented and what is yet to be implemented
- What are the changes compared to the sketch, how did we arrive at that decision?
- Only part of the release on github, no need to submit on gradescope.
- Should not be more than 500 words
- Location (`reports/m2-reflection.md`)

### Improve Readme
1. Those interested in using your dashboard
    - Include motivation behind your project and clearly explain
      what problem you are solving and why it is important.
    - You do not have to include detailed usage instructions,
      just high level what they can do in your dashboard and the deployed link.
    - [This is a good example](https://github.com/KirstieJane/STEMMRoleModels)
    - Include a link to your demo GIF in the README.
      It's sparks interest to see a demo of the app right away.
    - Include a note on how to get support (e.g. opening an issue).
2. Those interesting in running the app locally, and potentially helping you develop your dashboard
    - Potential contributors are interested in the above as well,
      but also need to know how they can install your app/dependencies and how to run it locally.
    - Include a link to the contributing file,
      where they can find out more if they are interested in making contributions to the repo.

**Comment by gtmx23** [comment]
Work division
- Every one to do one chart
  - Card: Gretel @gtmx23 
  - Pie Chart: Riya @riyaeliza123 
  - Line chart: Scout @scout-mckee 
  - Bar chart: Karan @karan-khubdikar 
- 2 widgets
  - **Provinces** (@karan-khubdikar seems to have started a bit already, can reference it)
  - Year (most of the other charts will vary by year - more interesting)
    - Potential idea: Put line chart at the bottom and make top 3 charts on top
- Try to finish technical stuff by Friday so we can go to the 532 lab to clarify thoughts
  - Writing to be done later (reflection part and stuff)
- Meeting on Friday 9 am Vancouver time (IRL for Vancouver friends) to discuss:
  - Work distribution for reflection and deployment (2 people to each section)
Note on dataset: Each row is copy of next row - need to remove alternate rows
- Remove the percentage row (UOM % thing) (@riyaeliza123 sorry I am not sure if I am understanding)

**Comment by gtmx23** [comment]
@karan-khubdikar I am kind of unfamiliar with the app stuff - would you mind pushing a copy of the practice code notebook you made on the repo for me to reference? we can delete it before the release :) we are meant to be working in a python script file right, does anyone want to create the first copy that we can all pull and edit from?

**Comment by karan-khubdikar** [comment]
Sure @gtmx23, I will push the reference code that I was practicing with based on the lecture notes. We can get rid of that later.

**Comment by karan-khubdikar** [comment]
Marking it completed as all the tasks have been done!
