### ISSUE TITLE
Line chart

### ISSUE THREAD

**Issue by scout-mckee** [UBC-MDS/DSCI-532_2024_13_Juno#33]
Line chart of % executive vs time for men and women. Interactive with provinces widget.

**Comment by riyaeliza123** [comment]
I've completed this one  - line-chart.py

**Comment by riyaeliza123** [comment]
<img width="911" alt="image" src="https://github.com/UBC-MDS/DSCI-532_2024_13_Juno/assets/85408127/1c30747c-e8e8-49f0-b4fd-8f0cb4a6bb8c">
This is what it looks like now!
