### ISSUE TITLE
Chart creation - pie chart

### ISSUE THREAD

**Issue by riyaeliza123** [UBC-MDS/DSCI-532_2024_13_Juno#34]
I'll create a pie chart showing the distribution of men and women in each sector

**Comment by riyaeliza123** [comment]
Prototype created. The pie_chart.py app works, but is not fully functional. As of now a basic chart renders with 2 dropdowns available. The dropdowns are not functional (there is an issue with the code not being able to read the variables from the dropdown, I will fix that soon). As of now we have a basic pie chart, new data filtered for the pie-chart and an ipynb file showing the expected working of the pie-chart.

**Comment by riyaeliza123** [comment]
<img width="953" alt="image" src="https://github.com/UBC-MDS/DSCI-532_2024_13_Juno/assets/85408127/971fd045-332b-454f-9d21-40a9b1bff806">
 This is what the chart looks like currently

**Comment by riyaeliza123** [comment]
<img width="893" alt="image" src="https://github.com/UBC-MDS/DSCI-532_2024_13_Juno/assets/85408127/f7bfe24c-ced1-4d5e-b044-3cc9f7e7df32">
Both drop downs are functional

**Comment by riyaeliza123** [comment]
This can be improved.. let's leave this task as optional for now

**Comment by karan-khubdikar** [comment]
Closing this issue as we can changed it into a bar chart as it makes more sense to show numbers on a bar.
