### ISSUE TITLE
Deployment Tasks

### ISSUE THREAD

**Issue by karan-khubdikar** [UBC-MDS/DSCI-532_2024_13_Juno#39]
Creating the checklist below for the tasks involved in the deployment of the dashboard:

- [x] Create an account on render (give access to the team as backup)
- [x] Create pip requirement file
- [x] Render the dashboard
- [x] Update the About Section
- [x] Create a GIF

**Comment by riyaeliza123** [comment]
@karan-khubdikar check the file pie_chart.py and advice on how to integrate it to app.py. Do we need to add all the apps right away (in this milestone) or can we have separate files for this milestone and combine them with modifications for the next milestone?

**Comment by riyaeliza123** [comment]
Environment file fixed and updated
use "conda" to install packages in the future, avoid "pip" as much as possible

**Comment by riyaeliza123** [comment]
Created requirements.txt, pushed to the pie-chart PR

**Comment by karan-khubdikar** [comment]
Thanks Riya, we have made some updates on the graphs. And the dashboard is getting deployed on render.

**Comment by karan-khubdikar** [comment]
Completed!
