### ISSUE TITLE
Create an "animation" of the app

### ISSUE THREAD

**Issue by riyaeliza123** [UBC-MDS/DSCI-532_2024_13_Juno#43]
Create an animation of your app in action and save it as img/demo.gif.
You can record your screen while demoing how the app updates when you make selections in the input widgets. If you don't have a local program for converting video to GIF, I have found [ezgif](https://ezgif.com/video-to-gif) quite helpful in the past.

**Comment by karan-khubdikar** [comment]
Thanks Riya. I have recorded the execution of my script. Will try using the ezgif website and see how it goes.

**Comment by karan-khubdikar** [comment]
Created the GIF. Just need to add the link in the Readme section. Marking this section as completed.
