### ISSUE TITLE
Feedback from Joel

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/DSCI-532_2024_13_Juno#60]
Major:
- [x] #63
    - [x] Either show a single year ration or average
- [x] #64
- [x] #65
    - [x] To be able to compare provinces

Minor:
- [x] #66
- [x] #68
    - [ ] E.g. Title background color?
    - [ ] Maybe something to separate widgets from chart/output
- [x] #69
- [x] #70
- [x] #71

**Comment by riyaeliza123** [comment]
we'll try a light gray bg with purple and green elements

**Comment by riyaeliza123** [comment]
Line closer to axis could not be done since there are multiple datasets involved in the creation of the line chart

**Comment by riyaeliza123** [comment]
After discussion, decided to use static map (chloropleth) to show provincial differences instead.
