### ISSUE TITLE
Updated App Sketch

### ISSUE THREAD

**Issue by gtmx23** [UBC-MDS/DSCI-532_2024_13_Juno#62]
Based on our discussion during lab time and taking into account Joel's comments
[App Sketch Week 3.pdf](https://github.com/UBC-MDS/DSCI-532_2024_13_Juno/files/14924253/App.Sketch.Week.3.pdf)

**Comment by riyaeliza123** [comment]
https://github.com/UBC-MDS/DSCI-532_2024_13_Juno/blob/main/img/App.Sketch.Week.3.pdf

**Comment by riyaeliza123** [comment]
Dashboard made according to this
