### ISSUE TITLE
Create teamwork contract

### ISSUE THREAD

**Issue by riyaeliza123** [UBC-MDS/DSCI-532_2024_13_Juno#7]
To be created and submitted to gradescope directly, don't push to github

**Comment by scout-mckee** [comment]
- made a google docs and sent in slack

**Comment by karan-khubdikar** [comment]
The contract looks good to me. I like how we have kept the deadline for submission floating given our deadlines also change during the quizzes and holidays!

**Comment by scout-mckee** [comment]
The .md document is saved in slack since we are not supposed to push it to GitHub.
