### ISSUE TITLE
Feedback from Nando

### ISSUE THREAD

**Issue by farrandi** [UBC-MDS/DSCI-532_2024_13_Juno#75]
- I see the percentage of men and women but it might be better to see it as a block/ pie chart with the proportions of men and women.
- Maybe add a map for the province selection, would be nicer to see and map visualizations are fun.
- Kind of difficult to understand the bar charts at a glance, making them smaller so that I do not have to scroll up or down to remember what I selected would be nice.
- Just some minor formatting so that I would know which selections would change which charts. Grouping them together in cards might help with this.

Overall, great dash! I’m jealous how fast your dash loads on [render.com](http://render.com/). Good topic to tackle too!

**Comment by riyaeliza123** [comment]
Thanks for the feedback! 
We will implement point 2, point 3 is done, point 4 is done, point 1 will not be done since the team loves the cards and want to keep them that way!

**Comment by gtmx23** [comment]
Thanks Nando! We appreciate the feedback :)

**Comment by karan-khubdikar** [comment]
Thank you, Nando for the feedback!

**Comment by riyaeliza123** [comment]
Addressed all as separate issues
