### ISSUE TITLE
20240410 Post-Quiz Dicussion: Work Distribution

### ISSUE THREAD

**Issue by gtmx23** [UBC-MDS/DSCI-532_2024_13_Juno#79]
Major
- [x] Change theme/stylistic elements @riyaeliza123 
- [x] Segment code into functions @scout-mckee 
  - Note: Might have a change to make on render - @scout-mckee will check! 
- [x] Add a static map chloropleth @karan-khubdikar 
- [x] Reflection/documentation stuff @gtmx23 
  - [x] Milestone reflection
  - [x] #95
  - [ ] Consider a learn more section to reveal description (lect 6) (or next week)
- [x] Add the national average to the line chart and add ratios @riyaeliza123 (DONE)

Minor 
- [ ] Submission 
- [x] Re-deploy on Render

More Minor (maybe next week)
- [x] Incorporate Nando's feedback: Move charts side by side to minimise scrolling 
- [x] Documentation on the sections
- [x] Get line chart closer to axes @riyaeliza123 
- [x] Indicate widget stuff (DONE)
- [ ] Flip y to x axes for bar chart to fix axis problem @karan-khubdikar 
- [ ] Potentially address TA feedback: It is not clear how the variables described are related to the problem that the dashboard is trying to address (data description in README)

Notes
- We collectively decided not to do the pie chart suggested by Nando, in favour of cards
- Riya is not available on the whole of Friday
- Scout is not available Friday night (happy birthday to friend!! :D)

**Comment by riyaeliza123** [comment]
The axis issue cant be fixed since we use multiple dfs in the creation of the chart

**Comment by gtmx23** [comment]
Ok! Thanks for the update, I will do a strikethrough on the task list!
