### ISSUE TITLE
Feedback from Jerry

### ISSUE THREAD

**Issue by jy1909** [UBC-MDS/DSCI-532_2024_13_Juno#84]
Overall, the dashboard conveys the information in a clear manner and is easy to use. It is also generally effective in fulfilling its purpose in "presenting the data in an easy to use and interpretable manner" to policy makers. Great work! Some suggestions are as follows:

Larger points:
- "Juno" in title: I understood what this means after I read your `README.md`. However, before I read the README, having this in the title seemed a little confusing to me. I would suggest adding a note at the bottom of the page to explain it.
- Filters that can "break" the app: currently, your filters work based on the assumption that they must take on a value. However, if the user accidentally click on the "x" in the filter, they can clear the filter and "break" the app by causing certain plots to only show their axes. If possible, make it so that the filters cannot be cleared.

Smaller points:
- Indicate numbers on line chart: because the ratios are quite similar, it is hard to tell the yearly changes. Labeling the ratio for each year on the chart would be a good idea to make it easier to read.
- Reformat the cards: The numbers in the cards should be larger since they should be empahsized to the users. I would recommend reorganizing the cards to put them side-by-side of each other.
- Reformat the graphs: The bar charts at the bottom of the page have their x-axis labels cut off. After selecting a different value in either the `Province` or the `Year` filter, the two charts at the bottom became narrower, making the bar on the right harder to read since its bars and labels are now smaller. I would be a good idea to polish these two charts. The line chart can use larger fonts for the title and axis labels so that they are easier to read.

**Comment by karan-khubdikar** [comment]
Thanks, Jerry for this feedback!! We are currently working on some and will see if we can incorporate the important ones by this week!

**Comment by riyaeliza123** [comment]
Thank you for the suggestions, we have fixed the first issue. The dashboard now has a drop down explaining what Juno means

**Comment by riyaeliza123** [comment]
All feedback has been addressed in separate issues.
