### ISSUE TITLE
Update: Friday PM

### ISSUE THREAD

**Issue by scout-mckee** [UBC-MDS/DSCI-532_2024_13_Juno#90]
Hi team! Just a brief update
Karan and I have been working together this afternoon and made some good progress. The dashboard still needs some modifications to make it look nicer/respond to feedback but we have a minimum viable product. 
As of this afternoon:
- the map is on the dashboard
- the functionality is in separate files
- we were able to deploy on render, yay!

Important note: 
The data file needs to be different to work on render, but is annoying to work with locally. So, this version is to that we can work locally and then when we are ready to use render, the data_render.py file will need to be renamed to data.py

**Comment by gtmx23** [comment]
Thanks so much for the good work! The render dashboard is working great for me, and the app.py code looks really clean, very impressive! 
What do you guys think about Jerry's feedback on the cards? We originally showed the cards side by side but changed it for this milestone - shall we stick to our own changes? Also, I noticed that the cards are still interactive - do we want them to remain interactive or do we want to change them to be static? I can help to change the code if we want them to be static, should not be a big issue! We also want 1 more card on the ratio of men to women right, do we want to incorporate that in this milestone or next week?

**Comment by karan-khubdikar** [comment]
I guess, we can make the changes to the cards if it does not take a lot of time. We can majorly focus on updating the layout and making it more presentable.

**Comment by gtmx23** [comment]
Sounds good! I guess we can leave it for now and maybe tackle it next week.

**Comment by karan-khubdikar** [comment]
Closing this issue as we do not have any tasks mentioned here and this was just an update about the work done.
