### ISSUE TITLE
Minor bugs

### ISSUE THREAD

**Issue by gtmx23** [UBC-MDS/DSCI-532_2024_13_Juno#94]
Hello! Thank you all for the great work so far :) I am not sure if it is because I am having trouble with my internet today, but I found a few minor issues:
- The GIF in the readme is not loading for me, on GH or locally. The caption/path seems fine so I am not sure what the problem is, will take another look soon and see if I can fix it
- I tried to install the Juno_environment as documented in the readme file, but the file is not working for me. I suspect it is due to the unique identifiers like `=pyhd8ed1ab_0` at the end of the versions. If it is alright, can I remove these identifiers and try again to use the environment? I am currently using the 532 environment with geopandas installed.

Will update if I encounter any more issues! I have just finished and pushed the reflection section, please do let me know if I missed out any changes or if there is anything you want to add! Will be working on adding the descriptions to the app.py file before making a PR.

**Comment by karan-khubdikar** [comment]
Fixed the environment file. It should be working fine now as I tried again and it worked in my local system.

**Comment by riyaeliza123** [comment]
gif fixed
